"""What kind of config this machine has, decided before the app writes anything (ADR-0009).

Exactly one of four cases holds on every start, and the whole first-run experience hangs
off which one: a normal run, an auto-offered Lua import, the migration wizard over the
hyprlang Importer, or a fresh empty App dir.

The uncertain case is decided deliberately, not accidentally. When a `hyprland.lua` exists
but the Manifest holds no record of the app having written one, this reports **foreign**.
Being wrong that way re-imports a file the app itself generated -- untidy, reversible, and
the original is kept as `hyprland.lua.bak` either way. Being wrong the other way lets the
Writer regenerate over a config the user hand-wrote, which is the one outcome ADR-0009
forbids outright ("must never *demolish* an existing config"). An asymmetric mistake gets
an asymmetric default.

Nothing here reads the config's *contents* except to spot Hyprland's own `autogenerated`
marker: detection decides which importer runs, and the importer is what understands files.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from ..paths import ConfigPaths
from ..state.manifest import Manifest, is_damaged

MARKER_SCAN_BYTES = 4096
"""How much of a `.conf` is read looking for `autogenerated`.

Hyprland writes the marker in the first few lines of the example config it ships. Reading a
bounded prefix rather than the whole tree keeps detection cheap enough to run on every
start, and a marker buried past 4 KB is not the pristine example config anyway.
"""


class ConfigKind(StrEnum):
    """The four mutually exclusive states a hypr config dir can be in (ADR-0009)."""

    APP_GENERATED = "app-generated"
    """A `hyprland.lua` this app wrote, vouched for by the Manifest. The normal run."""

    FOREIGN_LUA = "foreign-lua"
    """A `hyprland.lua` the app cannot claim. The Lua import flow is auto-offered."""

    LEGACY_CONF = "legacy-conf"
    """Only `hyprland.conf`. The migration wizard over the hyprlang Importer."""

    FRESH = "fresh"
    """Neither file. Generate an empty App dir and a working Entrypoint."""


@dataclass(frozen=True, slots=True)
class Detection:
    """The routing decision, and the evidence behind it."""

    kind: ConfigKind

    source: Path | None
    """The file an import would read, or `None` when there is nothing to import."""

    hand_edited: bool = False
    """An app-owned Entrypoint whose bytes no longer match the Manifest.

    Distinct from `FOREIGN_LUA`: the app knows it wrote this file, so the answer is the
    hand-edit consent gate (ADR-0005), never an offer to import the user's own config back
    over itself.
    """

    autogenerated: bool = False
    """The `.conf` carries Hyprland's `autogenerated = 1` marker.

    It is Hyprland's example config, not the user's work, so the wizard takes the
    streamlined path: no loss report to read, straight to convert.
    """

    @property
    def offers_import(self) -> bool:
        """Whether the app should offer to convert what it found."""
        return self.kind in (ConfigKind.FOREIGN_LUA, ConfigKind.LEGACY_CONF)

    @property
    def read_only(self) -> bool:
        """Whether settings pages must show but refuse to save.

        Until an offered import is accepted there is nowhere honest to write: the live
        session is still reading a file this app does not own (ADR-0009).
        """
        return self.offers_import

    @property
    def streamlined(self) -> bool:
        """Whether the wizard may skip the loss report (Hyprland's own example config)."""
        return self.kind is ConfigKind.LEGACY_CONF and self.autogenerated


def has_autogenerated_marker(path: Path, *, scan_bytes: int = MARKER_SCAN_BYTES) -> bool:
    """Whether a `hyprland.conf` is the stock example Hyprland generates for a new user.

    Matched on the assignment rather than the bare word, so a comment mentioning the marker
    -- or a user's own `$autogenerated` variable -- does not downgrade their real config to
    "not your work" and skip the loss report on it.
    """
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            head = handle.read(scan_bytes)
    except OSError:
        return False

    for line in head.splitlines():
        text = line.split("#", 1)[0].strip()
        key, separator, value = text.partition("=")
        if separator and key.strip() == "autogenerated" and value.strip() == "1":
            return True
    return False


def detect(paths: ConfigPaths, *, app_version: str, schema_version: str) -> Detection:
    """Which of ADR-0009's four cases this config dir is in.

    `app_version` and `schema_version` are the running app's, only so the Manifest can be
    loaded; a Manifest written by a different version still vouches for the Entrypoint it
    recorded, because the question here is "did we write this file", not "is it current".
    """
    entrypoint = paths.entrypoint
    if entrypoint.is_file():
        manifest = Manifest.load(
            paths.manifest, app_version=app_version, schema_version=schema_version
        )
        record = manifest.entrypoint
        if record is None:
            # No claim on the file. Damaged or absent Manifest lands here too, and the
            # safe-direction default above is what decides it.
            return Detection(kind=ConfigKind.FOREIGN_LUA, source=entrypoint)
        return Detection(
            kind=ConfigKind.APP_GENERATED,
            source=None,
            hand_edited=not record.matches(entrypoint) or is_damaged(paths.manifest),
        )

    conf = paths.hyprland_conf
    if conf.is_file():
        return Detection(
            kind=ConfigKind.LEGACY_CONF,
            source=conf,
            autogenerated=has_autogenerated_marker(conf),
        )

    return Detection(kind=ConfigKind.FRESH, source=None)
