-- generated by hyprland-settings-gui (PROTOTYPE)
hl.config({
  ['general.border_size'] = 7,
  ['decoration.rounding'] = 14,
  ['general.col.active_border'] = { colors = { '0xff00ffcc' }, angle = 45 },
  ['general.gaps_in'] = { top = 3, right = 3, bottom = 3, left = 3 },
})
