#!/usr/bin/env python3
"""PROTOTYPE — throwaway. A schema-driven Hyprland options page.

Question (issue #8): can a page generated purely from `hyprctl -j descriptions` (+ stubs)
look and behave well enough, or does each section need hand curation?

The whole point is the RAW / CURATED switch in the header bar: the same generator, the same
rows, the only difference being whether overlay.json is applied. Flip it while looking at
`input` and the answer is visible.

Run:  ./run.sh            (dry apply — prints the Lua it would write)
      ./run.sh --apply keyword     (live: hyprctl keyword, hyprlang session, instant)
      ./run.sh --apply lua         (writes a Lua module into ./out/ and reloads)
"""
import argparse, json, os, subprocess, sys, time

import gi
gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, Gtk, Gdk, GLib, Gio  # noqa: E402

import schema as schema_mod  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SENTINEL_STRINGS = ("[[EMPTY]]", "[[Auto]]")

FONT_WEIGHTS = [("Thin", 100), ("Ultralight", 200), ("Light", 300), ("Semilight", 350),
                ("Book", 380), ("Normal", 400), ("Medium", 500), ("Semibold", 600),
                ("Bold", 700), ("Ultrabold", 800), ("Heavy", 900), ("Ultraheavy", 1000)]


# ---------------------------------------------------------------- live values


def read_values(names):
    """One `hyprctl --batch` per page. Returns {name: (value, set_by_user)}."""
    if not names:
        return {}
    cmd = " ; ".join("j/getoption " + n for n in names)
    out = subprocess.run(["hyprctl", "--batch", cmd], capture_output=True, text=True).stdout
    dec, i, vals = json.JSONDecoder(), 0, {}
    while i < len(out):
        while i < len(out) and out[i] in " \n\r\t":
            i += 1
        if i >= len(out):
            break
        obj, i = dec.raw_decode(out, i)
        v = None
        # under hyprlang the complex types all come back as "custom"; under the Lua
        # engine they arrive as "gradient" / "css" / "font_weight" instead.
        for k in ("int", "float", "str", "vec2", "custom", "gradient", "css", "font_weight"):
            if k in obj:
                v = obj[k]
                break
        vals[obj["option"]] = (v, obj.get("set", False))
    return vals


def typed(rec, raw):
    """Coerce a getoption payload into the schema type."""
    t = rec["type"]
    if raw is None:
        return rec["default"]
    if t == "bool":
        return bool(raw)
    if t == "color":
        return "%08x" % (int(raw) & 0xFFFFFFFF) if int(raw) != -1 else "-1"
    if t in ("int",):
        return int(raw)
    if t == "float":
        return float(raw)
    if t == "vec2":
        return list(raw)
    return raw


# ---------------------------------------------------------------- lua emission


def lua_literal(rec, value):
    """Lua does NOT accept the `toString()` text that `descriptions` prints for the
    complex types: a gradient string is parsed as a single colour and a css-gap string
    is rejected outright. Gradient and css-gaps must be emitted as tables
    (HL.Gradient = {colors, angle}, HL.CssGap = {top,right,bottom,left})."""
    t = rec["type"]
    if t == "bool":
        return "true" if value else "false"
    if t in ("int", "float"):
        return repr(value)
    if t == "vec2":
        return "{ %s, %s }" % (value[0], value[1])
    if t == "color":
        return "'0x%s'" % value if value != "-1" else "-1"
    if t == "gradient":
        parts = str(value).split()
        angle = 0
        if parts and parts[-1].endswith("deg"):
            angle = int(float(parts[-1][:-3]))
            parts = parts[:-1]
        colors = ", ".join("'0x%s'" % p for p in parts)
        return "{ colors = { %s }, angle = %d }" % (colors, angle)
    if t == "css_gaps":
        n = [int(float(x)) for x in str(value).split()] or [0]
        while len(n) < 4:
            n.append(n[-1])
        return "{ top = %d, right = %d, bottom = %d, left = %d }" % tuple(n[:4])
    if t == "font_weight":
        return "'%s'" % value
    return "'%s'" % str(value).replace("'", "\\'")


def lua_module(pending):
    """pending: [(rec, value)] -> a hl.config module, the real write path (ADR-0002)."""
    lines = ["-- generated by hyprland-settings-gui (PROTOTYPE)", "hl.config({"]
    for rec, value in pending:
        lines.append("  ['%s'] = %s," % (schema_mod.lua_key(rec["name"]), lua_literal(rec, value)))
    lines += ["})", ""]
    return "\n".join(lines)


def hyprlang_value(rec, value):
    t = rec["type"]
    if t == "bool":
        return "true" if value else "false"
    if t == "vec2":
        return "%s %s" % (value[0], value[1])
    if t == "color":
        return "rgba(%s)" % value if value != "-1" else "-1"
    return str(value)


# ---------------------------------------------------------------- applier


class Applier:
    def __init__(self, mode, out_dir):
        self.mode = mode
        self.out_dir = out_dir
        self.log = []          # [(name, value, mode, ms, note)]
        os.makedirs(out_dir, exist_ok=True)
        self.state = {}        # name -> value, everything written so far

    def apply(self, rec, value):
        t0 = time.perf_counter()
        note = ""
        self.state[rec["name"]] = value
        if self.mode == "keyword":
            r = subprocess.run(["hyprctl", "keyword", rec["name"], hyprlang_value(rec, value)],
                               capture_output=True, text=True)
            note = r.stdout.strip() or r.stderr.strip()
        elif self.mode == "lua":
            recs = [(rec, value)]
            path = os.path.join(self.out_dir, "options.lua")
            tmp = path + ".tmp"
            open(tmp, "w").write(lua_module(list(self._all_pending())))
            os.replace(tmp, path)
            r = subprocess.run(["hyprctl", "reload"], capture_output=True, text=True)
            note = r.stdout.strip()
        else:
            note = lua_module([(rec, value)]).strip().splitlines()[-2]
        ms = (time.perf_counter() - t0) * 1000
        self.log.append((rec["name"], value, self.mode, ms, note))
        return ms, note

    def _all_pending(self):
        return [(RECS_BY_NAME[n], v) for n, v in self.state.items()]


RECS_BY_NAME = {}


# ---------------------------------------------------------------- defect rules

PICKER_HINTS = {
    "font": ("font_family",), "monitor": ("output", "default_monitor"),
    "file": ("kb_file", "screen_shader"), "regex": ("regex",),
    "xkb": ("kb_layout", "kb_variant", "kb_options", "kb_model", "kb_rules"),
}
UNIT_PAT = [(" in ms", "ms"), ("in ms", "ms"), (" ms", "ms"), ("in px", "px"),
            ("in degrees", "deg"), ("in seconds", "s"), ("percent", "%")]


def defects(rec):
    """Machine-checkable ways a purely generated row is wrong/unhelpful."""
    d = []
    name, desc = rec["name"], (rec["description"] or "").lower()
    if rec["widget"] in ("int-range", "free-int") and rec["map"] is None \
            and rec["max"] is not None and rec["max"] <= 6 and rec["min"] is not None:
        d.append("enum-as-number")
    if rec["default"] in SENTINEL_STRINGS or rec["default"] == -1 or rec["default"] == "-1":
        d.append("sentinel-shown-literally")
    if any(u in desc for u, _ in UNIT_PAT) and rec["type"] in ("int", "float", "vec2"):
        d.append("unit-missing")
    for kind, keys in PICKER_HINTS.items():
        if rec["widget"] in ("string", "enum-string") and any(k in name for k in keys):
            d.append("needs-%s-picker" % kind)
    if any(p in desc for p in ("only used", "only works", "requires ", "when using", "needs ")):
        d.append("dependency-not-modelled")
    if rec["type"] in ("int", "float") and (rec["min"] is None or rec["max"] is None):
        d.append("unbounded-numeric")
    if rec["section"] in ("debug", "quirks", "experimental", "input-capture"):
        d.append("should-be-hidden")
    if rec["widget"] == "vec2" and not rec["vec2_range"]:
        d.append("vec2-unbounded")
    if rec["widget"] == "string" and rec["type"] == "string" and not rec["choices"] \
            and "needs-font-picker" not in d and "needs-monitor-picker" not in d \
            and "needs-file-picker" not in d and "needs-regex-picker" not in d \
            and "needs-xkb-picker" not in d and "[" in (rec["description"] or ""):
        d.append("choices-in-prose")
    return d


# ---------------------------------------------------------------- rows


class Page(Adw.PreferencesPage):
    def __init__(self, win, section, recs, values, curated):
        super().__init__()
        self.win, self.curated = win, curated
        self.set_title(section)
        groups = schema_mod.groups_for(section, curated)
        shown = [r for r in recs if r["visibility"] != "hidden" or win.show_advanced]
        if not win.show_advanced:
            shown = [r for r in shown if r["visibility"] != "advanced"]
        by_name = {r["name"]: r for r in shown}
        placed = set()
        if groups:
            for g in groups:
                grp = Adw.PreferencesGroup(title=g["title"])
                if g.get("description"):
                    grp.set_description(g["description"])
                any_row = False
                for n in g["options"]:
                    if n in by_name:
                        grp.add(self.row(by_name[n], values))
                        placed.add(n)
                        any_row = True
                if any_row:
                    self.add(grp)
        rest = [r for r in shown if r["name"] not in placed]
        if rest:
            grp = Adw.PreferencesGroup(title="Other" if groups else section)
            if not curated:
                grp.set_description("generated from `hyprctl -j descriptions`, no curation")
            for r in rest:
                grp.add(self.row(r, values))
            self.add(grp)

    # -- helpers

    def subtitle(self, rec):
        if self.curated and rec.get("help"):
            return rec["help"]
        return rec["description"]

    def label(self, rec):
        return rec["title"] if self.curated else rec["name"]

    def commit(self, rec, value):
        self.win.commit(rec, value)

    def with_reset(self, rec, row, getter, setter, values):
        cur, was_set = values.get(rec["name"], (None, False))
        btn = Gtk.Button(icon_name="edit-undo-symbolic", valign=Gtk.Align.CENTER)
        btn.add_css_class("flat")
        btn.set_tooltip_text("Reset to default (%s)" % rec["default"])
        btn.connect("clicked", lambda *_: setter(rec["default"]))
        btn.set_visible(getter() != rec["default"])
        row.add_suffix(btn)
        self.win.reset_buttons.append((rec, btn, getter))
        if self.curated and rec.get("restart"):
            lbl = Gtk.Label(label="restart", valign=Gtk.Align.CENTER)
            lbl.add_css_class("dim-label")
            lbl.add_css_class("caption")
            row.add_suffix(lbl)
        if self.curated and rec.get("help_url"):
            link = Gtk.Button(icon_name="help-about-symbolic", valign=Gtk.Align.CENTER)
            link.add_css_class("flat")
            link.set_tooltip_text(rec["help_url"])
            link.connect("clicked", lambda *_: Gio.AppInfo.launch_default_for_uri(rec["help_url"], None))
            row.add_suffix(link)
        if self.curated and rec.get("device_overridable_badge"):
            pass
        return row

    # -- widget per kind

    def row(self, rec, values):
        v = typed(rec, values.get(rec["name"], (None, False))[0])
        w = rec["widget"]
        if self.curated and rec.get("widget"):
            w = rec["widget"]
        fn = getattr(self, "row_" + w.replace("-", "_"), None) or self.row_string
        row = fn(rec, v, values)
        if self.curated and rec.get("depends_on"):
            dep = rec["depends_on"]
            depv = typed(RECS_BY_NAME[dep["option"]], values.get(dep["option"], (None, False))[0])
            if depv != dep["value"]:
                row.set_sensitive(False)
                note = "needs %s = %s" % (RECS_BY_NAME[dep["option"]]["title"], dep["value"])
                if hasattr(row, "set_subtitle"):
                    row.set_subtitle(self.subtitle(rec) + "  ·  " + note)
                else:
                    row.set_tooltip_text(note)
        return row

    def unit_suffix(self, rec):
        return (" (%s)" % rec["unit"]) if (self.curated and rec.get("unit")) else ""

    def row_toggle(self, rec, v, values):
        row = Adw.SwitchRow(title=self.label(rec), subtitle=self.subtitle(rec))
        row.set_active(bool(v))
        row.connect("notify::active", lambda r, _: self.commit(rec, r.get_active()))
        return self.with_reset(rec, row, row.get_active, row.set_active, values)

    def _spin(self, rec, v, values, digits, lo, hi, step):
        row = Adw.SpinRow(title=self.label(rec) + self.unit_suffix(rec), subtitle=self.subtitle(rec),
                          adjustment=Gtk.Adjustment(lower=lo, upper=hi, step_increment=step,
                                                    page_increment=step * 10))
        row.set_digits(digits)
        row.set_value(v if v is not None else 0)
        row.connect("notify::value", lambda r, _: self.commit(
            rec, int(r.get_value()) if digits == 0 else round(r.get_value(), digits)))
        return self.with_reset(rec, row, (lambda: int(row.get_value()) if digits == 0 else round(row.get_value(), digits)),
                               row.set_value, values)

    def row_int_range(self, rec, v, values):
        lo = rec["min"] if rec["min"] is not None else -10000
        hi = rec["max"] if rec["max"] is not None else 10000
        if self.curated and rec.get("range"):
            lo, hi = rec["range"].get("min", lo), rec["range"].get("max", hi)
        return self._spin(rec, v, values, 0, lo, hi, 1)

    def row_free_int(self, rec, v, values):
        hi = rec["max"] if rec["max"] not in (None, 2**31 - 1) else 100000
        if self.curated and rec.get("range"):
            hi = rec["range"].get("soft_max", hi)
        return self._spin(rec, v, values, 0, rec["min"] or 0, hi, 1)

    def row_float_range(self, rec, v, values):
        lo = rec["min"] if rec["min"] is not None else -1000.0
        hi = rec["max"] if rec["max"] is not None else 1000.0
        step = 0.01 if (hi - lo) <= 10 else 0.1
        return self._spin(rec, v, values, 2, lo, hi, step)

    def row_free_float(self, rec, v, values):
        return self._spin(rec, v, values, 2, -1000.0, 1000.0, 0.1)

    def row_enum_map(self, rec, v, values):
        items = sorted((rec["map"] or {}).items(), key=lambda kv: kv[1])
        labels = rec.get("labels") if self.curated else None
        texts = [(labels or {}).get(str(val), key.replace("_", " ").capitalize() if self.curated else key)
                 for key, val in items]
        vals = [val for _, val in items]
        row = Adw.ComboRow(title=self.label(rec), subtitle=self.subtitle(rec),
                           model=Gtk.StringList.new(texts))
        if v in vals:
            row.set_selected(vals.index(v))
        row.connect("notify::selected", lambda r, _: self.commit(rec, vals[r.get_selected()]))
        return self.with_reset(rec, row,
                               lambda: vals[row.get_selected()] if row.get_selected() < len(vals) else None,
                               lambda d: row.set_selected(vals.index(d)) if d in vals else None, values)

    def row_enum_string(self, rec, v, values):
        choices = list(rec.get("known_values") or rec.get("choices") or [])
        labels = rec.get("labels") if self.curated else None
        nullable = self.curated and rec.get("nullable")
        display = list(choices)
        if nullable:
            display = [rec.get("null_label", "Default")] + display
        texts = [(labels or {}).get(c, c) for c in display]
        row = Adw.ComboRow(title=self.label(rec), subtitle=self.subtitle(rec),
                           model=Gtk.StringList.new(texts))
        cur = v if v not in SENTINEL_STRINGS else None
        if nullable and cur is None:
            row.set_selected(0)
        elif cur in display:
            row.set_selected(display.index(cur))

        def val():
            i = row.get_selected()
            return "" if (nullable and i == 0) else display[i]
        row.connect("notify::selected", lambda r, _: self.commit(rec, val()))
        return self.with_reset(rec, row, val,
                               lambda d: row.set_selected(display.index(d) if d in display else 0), values)

    def row_string(self, rec, v, values):
        row = Adw.EntryRow(title=self.label(rec))
        shown = "" if v in SENTINEL_STRINGS else str(v)
        row.set_text(shown)
        if self.curated and rec.get("placeholder"):
            row.set_show_apply_button(True)
        row.set_tooltip_text(self.subtitle(rec))
        sub = Adw.ActionRow(title=self.label(rec), subtitle=self.subtitle(rec))
        row.connect("apply", lambda r: self.commit(rec, r.get_text()))
        row.connect("changed", lambda r: self.commit(rec, r.get_text()))
        return self.with_reset(rec, row, row.get_text,
                               lambda d: row.set_text("" if d in SENTINEL_STRINGS else str(d)), values)

    def row_font_picker(self, rec, v, values):
        row = Adw.ActionRow(title=self.label(rec), subtitle=self.subtitle(rec))
        btn = Gtk.FontDialogButton(dialog=Gtk.FontDialog(), valign=Gtk.Align.CENTER)
        btn.set_level(Gtk.FontLevel.FAMILY)
        try:
            from gi.repository import Pango
            btn.set_font_desc(Pango.FontDescription.from_string(str(v)))
        except Exception:
            pass
        btn.connect("notify::font-desc", lambda b, _: self.commit(rec, b.get_font_desc().get_family()))
        row.add_suffix(btn)
        return self.with_reset(rec, row, lambda: btn.get_font_desc().get_family(),
                               lambda d: None, values)

    def row_monitor_picker(self, rec, v, values):
        mons = ["(auto)"]
        try:
            mons += [m["name"] for m in json.loads(
                subprocess.run(["hyprctl", "-j", "monitors"], capture_output=True, text=True).stdout)]
        except Exception:
            pass
        row = Adw.ComboRow(title=self.label(rec), subtitle=self.subtitle(rec),
                           model=Gtk.StringList.new(mons))
        if v in mons:
            row.set_selected(mons.index(v))
        row.connect("notify::selected", lambda r, _: self.commit(
            rec, "" if r.get_selected() == 0 else mons[r.get_selected()]))
        return self.with_reset(rec, row, lambda: mons[row.get_selected()],
                               lambda d: row.set_selected(0), values)

    def row_file_picker(self, rec, v, values):
        row = Adw.ActionRow(title=self.label(rec), subtitle=self.subtitle(rec))
        btn = Gtk.Button(label=os.path.basename(str(v)) or "Choose…", valign=Gtk.Align.CENTER)
        row.add_suffix(btn)
        return self.with_reset(rec, row, lambda: btn.get_label(), lambda d: None, values)

    def row_regex(self, rec, v, values):
        row = Adw.EntryRow(title=self.label(rec))
        row.set_text("" if v in SENTINEL_STRINGS else str(v))

        def on_change(r):
            import re as _re
            try:
                _re.compile(r.get_text())
                r.remove_css_class("error")
                self.commit(rec, r.get_text())
            except _re.error:
                r.add_css_class("error")
        row.connect("changed", on_change)
        return self.with_reset(rec, row, row.get_text, lambda d: row.set_text(""), values)

    def row_color(self, rec, v, values):
        row = Adw.ActionRow(title=self.label(rec), subtitle=self.subtitle(rec))
        btn = Gtk.ColorDialogButton(dialog=Gtk.ColorDialog(), valign=Gtk.Align.CENTER)
        rgba = Gdk.RGBA()
        if v and v != "-1":
            a, r_, g, b = (int(v[0:2], 16), int(v[2:4], 16), int(v[4:6], 16), int(v[6:8], 16))
            rgba.red, rgba.green, rgba.blue, rgba.alpha = r_ / 255, g / 255, b / 255, a / 255
        btn.set_rgba(rgba)

        def to_hex():
            c = btn.get_rgba()
            return "%02x%02x%02x%02x" % (int(c.alpha * 255), int(c.red * 255), int(c.green * 255), int(c.blue * 255))
        btn.connect("notify::rgba", lambda b, _: self.commit(rec, to_hex()))
        if self.curated and rec.get("nullable"):
            inh = Gtk.CheckButton(label=rec.get("null_label", "Inherit"), valign=Gtk.Align.CENTER)
            inh.set_active(v == "-1")
            inh.connect("toggled", lambda c: (btn.set_sensitive(not c.get_active()),
                                              self.commit(rec, "-1" if c.get_active() else to_hex())))
            btn.set_sensitive(not inh.get_active())
            row.add_suffix(inh)
        row.add_suffix(btn)
        return self.with_reset(rec, row, to_hex, lambda d: None, values)

    def row_gradient(self, rec, v, values):
        parts = str(v).split()
        angle = 0
        if parts and parts[-1].endswith("deg"):
            angle = int(float(parts[-1][:-3]))
            parts = parts[:-1]
        row = Adw.ExpanderRow(title=self.label(rec), subtitle=self.subtitle(rec))
        swatch = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=2, valign=Gtk.Align.CENTER)
        btns = []
        for stop in parts or ["ffffffff"]:
            b = Gtk.ColorDialogButton(dialog=Gtk.ColorDialog(), valign=Gtk.Align.CENTER)
            c = Gdk.RGBA()
            try:
                a, r_, g, bl = (int(stop[0:2], 16), int(stop[2:4], 16), int(stop[4:6], 16), int(stop[6:8], 16))
                c.red, c.green, c.blue, c.alpha = r_ / 255, g / 255, bl / 255, a / 255
            except Exception:
                pass
            b.set_rgba(c)
            btns.append(b)
            swatch.append(b)
        row.add_suffix(swatch)
        arow = Adw.SpinRow(title="Angle (deg)", adjustment=Gtk.Adjustment(lower=0, upper=359, step_increment=1))
        arow.set_value(angle)
        row.add_row(arow)

        def emit():
            stops = []
            for b in btns:
                c = b.get_rgba()
                stops.append("%02x%02x%02x%02x" % (int(c.alpha * 255), int(c.red * 255),
                                                   int(c.green * 255), int(c.blue * 255)))
            self.commit(rec, " ".join(stops) + " %ddeg" % int(arow.get_value()))
        for b in btns:
            b.connect("notify::rgba", lambda *_: emit())
        arow.connect("notify::value", lambda *_: emit())
        if self.curated and rec.get("nullable"):
            inh = Gtk.CheckButton(label=rec.get("null_label", "Inherit"), valign=Gtk.Align.CENTER)
            row.add_suffix(inh)
        return self.with_reset(rec, row, lambda: str(v), lambda d: None, values)

    def row_css_gaps(self, rec, v, values):
        nums = [int(float(x)) for x in str(v).split()] or [0, 0, 0, 0]
        while len(nums) < 4:
            nums.append(nums[-1])
        uniform = len(set(nums)) == 1
        row = Adw.ExpanderRow(title=self.label(rec) + self.unit_suffix(rec), subtitle=self.subtitle(rec))
        spins = []
        if self.curated:
            uni = Adw.SwitchRow(title="Same on all sides")
            uni.set_active(uniform)
            row.add_row(uni)
        for i, side in enumerate(["Top", "Right", "Bottom", "Left"]):
            s = Adw.SpinRow(title=side if self.curated else "%s[%d]" % (rec["name"].split(":")[-1], i),
                            adjustment=Gtk.Adjustment(lower=0, upper=200, step_increment=1))
            s.set_value(nums[i])
            spins.append(s)
            row.add_row(s)

        def emit(*_):
            vals = [int(s.get_value()) for s in spins]
            if self.curated and uni.get_active():
                vals = [vals[0]] * 4
                for s in spins[1:]:
                    s.set_value(vals[0])
            self.commit(rec, " ".join(str(x) for x in vals))
        for s in spins:
            s.connect("notify::value", emit)
        if self.curated:
            for i, s in enumerate(spins):
                s.set_visible(True)
            uni.connect("notify::active", lambda *_: [s.set_visible(not uni.get_active() or i == 0)
                                                      for i, s in enumerate(spins)])
            for i, s in enumerate(spins):
                s.set_visible(not uni.get_active() or i == 0)
            spins[0].set_title("All sides" if uni.get_active() else "Top")
        return self.with_reset(rec, row, lambda: str(v), lambda d: None, values)

    def row_vec2(self, rec, v, values):
        rng = (rec.get("range") if self.curated else None) or rec.get("vec2_range")
        lo, hi = (-10000.0, 10000.0)
        if isinstance(rng, dict):
            lo, hi = float(rng.get("min", lo)), float(rng.get("max", hi))
        elif isinstance(rng, (list, tuple)) and len(rng) == 4:
            f = [float(x) for x in rng]
            lo, hi = min(f[0], f[1]), max(f[2], f[3])
        row = Adw.ExpanderRow(title=self.label(rec) + self.unit_suffix(rec), subtitle=self.subtitle(rec))
        sx = Adw.SpinRow(title="X" if self.curated else "x",
                         adjustment=Gtk.Adjustment(lower=lo, upper=hi, step_increment=1))
        sy = Adw.SpinRow(title="Y" if self.curated else "y",
                         adjustment=Gtk.Adjustment(lower=lo, upper=hi, step_increment=1))
        sx.set_digits(2), sy.set_digits(2)
        sx.set_value(float(v[0])), sy.set_value(float(v[1]))
        row.add_row(sx), row.add_row(sy)
        for s in (sx, sy):
            s.connect("notify::value", lambda *_: self.commit(rec, [round(sx.get_value(), 2), round(sy.get_value(), 2)]))
        return self.with_reset(rec, row, lambda: [round(sx.get_value(), 2), round(sy.get_value(), 2)],
                               lambda d: None, values)

    def row_font_weight(self, rec, v, values):
        names = [n for n, _ in FONT_WEIGHTS]
        vals = [w for _, w in FONT_WEIGHTS]
        if not self.curated:
            return self._spin(rec, int(v), values, 0, 100, 1000, 100)
        row = Adw.ComboRow(title=self.label(rec), subtitle=self.subtitle(rec),
                           model=Gtk.StringList.new(names))
        try:
            row.set_selected(vals.index(int(v)))
        except ValueError:
            row.set_selected(5)
        row.connect("notify::selected", lambda r, _: self.commit(rec, str(vals[r.get_selected()])))
        return self.with_reset(rec, row, lambda: str(vals[row.get_selected()]), lambda d: None, values)

    def row_segmented(self, rec, v, values):
        """Curated widget: map-less int enum rendered with real labels."""
        labels = rec.get("labels") or {}
        vals = sorted(int(k) for k in labels)
        texts = [labels[str(k)] for k in vals]
        row = Adw.ComboRow(title=self.label(rec), subtitle=self.subtitle(rec),
                           model=Gtk.StringList.new(texts))
        if int(v) in vals:
            row.set_selected(vals.index(int(v)))
        row.connect("notify::selected", lambda r, _: self.commit(rec, vals[r.get_selected()]))
        return self.with_reset(rec, row, lambda: vals[row.get_selected()],
                               lambda d: row.set_selected(vals.index(int(d)) if int(d) in vals else 0), values)

    row_xkb_layout = row_enum_string
    row_float_list = row_string


# ---------------------------------------------------------------- window


class Win(Adw.ApplicationWindow):
    def __init__(self, app, sections, applier, curated, show_advanced):
        super().__init__(application=app, title="Hyprland Settings — PROTOTYPE (#8)")
        self.set_default_size(1080, 860)
        self.applier = applier
        self.curated = curated
        self.show_advanced = show_advanced
        self.sections = sections
        self.reset_buttons = []
        self.toast = Adw.ToastOverlay()

        self.switch = Gtk.Switch(valign=Gtk.Align.CENTER, active=curated)
        self.switch.connect("notify::active", lambda *_: self.rebuild())
        box = Gtk.Box(spacing=6)
        box.append(Gtk.Label(label="Curated"))
        box.append(self.switch)
        adv = Gtk.ToggleButton(label="Advanced", active=show_advanced, valign=Gtk.Align.CENTER)
        adv.connect("toggled", lambda b: (setattr(self, "show_advanced", b.get_active()), self.rebuild()))

        self.header = Adw.HeaderBar()
        self.header.pack_end(box)
        self.header.pack_end(adv)
        self.status = Gtk.Label(label="apply mode: %s" % applier.mode)
        self.status.add_css_class("dim-label")
        self.header.pack_start(self.status)

        self.stack = Adw.ViewStack()
        self.sidebar_list = Gtk.ListBox()
        self.sidebar_list.add_css_class("navigation-sidebar")
        self.sidebar_list.connect("row-selected", self.on_section)

        sidebar = Adw.NavigationPage(title="Sections",
                                     child=self._toolbar(Adw.HeaderBar(), Gtk.ScrolledWindow(child=self.sidebar_list)))
        self.content_tv = self._toolbar(self.header, self.stack)
        self.content_page = Adw.NavigationPage(title="Options", child=self.content_tv)
        split = Adw.NavigationSplitView(sidebar=sidebar, content=self.content_page)
        split.set_min_sidebar_width(200)
        self.toast.set_child(split)
        self.set_content(self.toast)
        self.rebuild()

    def _toolbar(self, header, child):
        tv = Adw.ToolbarView()
        tv.add_top_bar(header)
        tv.set_content(child)
        return tv

    def rebuild(self):
        self.curated = self.switch.get_active()
        recs = schema_mod.build(curated=self.curated)
        RECS_BY_NAME.clear()
        RECS_BY_NAME.update({r["name"]: r for r in recs})
        self.reset_buttons = []
        sel = self.sidebar_list.get_selected_row()
        idx = sel.get_index() if sel else 0
        while self.sidebar_list.get_first_child():
            self.sidebar_list.remove(self.sidebar_list.get_first_child())
        self.stack = Adw.ViewStack()
        for s in self.sections:
            page_recs = [r for r in recs if r["section"] == s]
            values = read_values([r["name"] for r in page_recs])
            page = Page(self, s, page_recs, values, self.curated)
            sw = Gtk.ScrolledWindow(child=page)
            self.stack.add_titled(sw, s, s)
            row = Adw.ActionRow(title=s, subtitle="%d options" % len(page_recs))
            self.sidebar_list.append(row)
        self.content_tv.set_content(self.stack)
        rows = [self.sidebar_list.get_row_at_index(i) for i in range(len(self.sections))]
        if rows and rows[idx]:
            self.sidebar_list.select_row(rows[idx])
        self.status.set_label("%s · apply: %s" % ("curated" if self.curated else "RAW (generated only)",
                                                  self.applier.mode))

    def on_section(self, _lb, row):
        if row:
            self.stack.set_visible_child_name(self.sections[row.get_index()])

    def commit(self, rec, value):
        ms, note = self.applier.apply(rec, value)
        t = Adw.Toast.new("%s = %s   (%s, %.0f ms)" % (rec["title"] if self.curated else rec["name"],
                                                       value, self.applier.mode, ms))
        t.set_timeout(2)
        self.toast.add_toast(t)
        print("[apply] %-46s %-24s %6.1f ms  %s" % (rec["name"], value, ms, note), flush=True)
        for r, btn, getter in self.reset_buttons:
            if r["name"] == rec["name"]:
                try:
                    btn.set_visible(getter() != r["default"])
                except Exception:
                    pass


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sections", default="input,decoration,general")
    ap.add_argument("--apply", default="dry", choices=["dry", "keyword", "lua"])
    ap.add_argument("--out", default=os.path.join(HERE, "out"))
    ap.add_argument("--raw", action="store_true", help="start on the uncurated side")
    ap.add_argument("--advanced", action="store_true")
    args = ap.parse_args()

    applier = Applier(args.apply, args.out)
    sections = args.sections.split(",")
    app = Adw.Application(application_id="dev.prototype.hyprsettings8")
    app.connect("activate", lambda a: Win(a, sections, applier, not args.raw, args.advanced).present())
    app.run([])


if __name__ == "__main__":
    main()
