#!/usr/bin/env python3
"""PROTOTYPE — instant-apply latency against a NESTED Hyprland running the Lua engine.

Three paths from docs/research/live-apply.md section 8 are timed:
  eval      `hyprctl eval 'hl.config{...}'`      — live preview, wiped by next reload
  rename    atomic rename + explicit `hyprctl reload`, wait for socket2 `configreloaded`
  inplace   truncate+write in place, wait for the watcher's own IN_CLOSE_WRITE reload

Usage:  HYPRLAND_INSTANCE_SIGNATURE=<nested sig> python3 measure.py [iterations]
"""
import json, os, socket, statistics, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
MODULE = os.path.join(HERE, "nested", "options.lua")
SIG = os.environ["HYPRLAND_INSTANCE_SIGNATURE"]
RUN = os.environ.get("XDG_RUNTIME_DIR", "/run/user/1000")
SOCK2 = os.path.join(RUN, "hypr", SIG, ".socket2.sock")


SOCK1 = os.path.join(RUN, "hypr", SIG, ".socket.sock")


def hyprctl(*args):
    """The obvious implementation: spawn the hyprctl binary."""
    return subprocess.run(["hyprctl", *args], capture_output=True, text=True).stdout.strip()


def ipc(command):
    """What the app should actually do: speak the IPC socket directly, no process spawn."""
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.connect(SOCK1)
    s.sendall(command.encode())
    out = b""
    while True:
        chunk = s.recv(8192)
        if not chunk:
            break
        out += chunk
    s.close()
    return out.decode().strip()


def drain(sock):
    """Discard buffered events so the next wait_for() times a fresh one."""
    sock.setblocking(False)
    try:
        while sock.recv(65536):
            pass
    except (BlockingIOError, socket.timeout):
        pass
    sock.setblocking(True)


def module_text(border):
    return ("-- generated by hyprland-settings-gui (PROTOTYPE)\n"
            "hl.config({\n  ['general.border_size'] = %d,\n})\n" % border)


def wait_for(sock, needle, timeout=3.0):
    sock.settimeout(timeout)
    t0 = time.perf_counter()
    buf = b""
    while time.perf_counter() - t0 < timeout:
        try:
            chunk = sock.recv(4096)
        except socket.timeout:
            break
        if not chunk:
            break
        buf += chunk
        if needle in buf:
            return time.perf_counter()
    return None


def getoption_int(name):
    return json.loads(hyprctl("-j", "getoption", name)).get("int")


def poll_until(name, want, timeout=3.0):
    """Wall-clock instant: the moment the compositor actually reports the new value."""
    t0 = time.perf_counter()
    while time.perf_counter() - t0 < timeout:
        try:
            if json.loads(ipc("-j/getoption " + name)).get("int") == want:
                return time.perf_counter()
        except Exception:
            pass
    return time.perf_counter()


def run(iterations=10):
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.connect(SOCK2)
    results = {"eval_spawn": [], "eval_ipc": [], "rename": [], "rename_applied": [],
               "inplace": [], "inplace_applied": [],
               "verify_spawn": [], "verify_ipc": [], "spawn_overhead": []}
    bad = 0

    for i in range(iterations):
        border = 1 + (i % 8)

        # --- eval (live preview path), both transports
        t0 = time.perf_counter()
        hyprctl("eval", "hl.config{general={border_size=%d}}" % border)
        results["eval_spawn"].append((time.perf_counter() - t0) * 1000)
        t0 = time.perf_counter()
        ipc("/eval hl.config{general={border_size=%d}}" % border)
        results["eval_ipc"].append((time.perf_counter() - t0) * 1000)

        # --- atomic rename + explicit reload, timed to the socket2 confirmation
        text = module_text(border)
        tmp = MODULE + ".tmp"
        open(tmp, "w").write(text)
        drain(s)
        t0 = time.perf_counter()
        os.replace(tmp, MODULE)
        ipc("/reload")
        t1 = wait_for(s, b"configreloaded")
        results["rename"].append(((t1 or time.perf_counter()) - t0) * 1000)

        results["rename_applied"].append((poll_until("general:border_size", border) - t0) * 1000)

        tv = time.perf_counter()
        got = json.loads(ipc("-j/getoption general:border_size")).get("int")
        results["verify_ipc"].append((time.perf_counter() - tv) * 1000)
        tv = time.perf_counter()
        getoption_int("general:border_size")
        results["verify_spawn"].append((time.perf_counter() - tv) * 1000)
        results["spawn_overhead"].append(results["verify_spawn"][-1] - results["verify_ipc"][-1])
        ok = got == border

        # --- in-place write, no explicit reload (watcher's IN_CLOSE_WRITE)
        border2 = 1 + ((i + 4) % 8)
        drain(s)
        t0 = time.perf_counter()
        with open(MODULE, "w") as f:
            f.write(module_text(border2))
        t1 = wait_for(s, b"configreloaded")
        results["inplace"].append(((t1 or time.perf_counter()) - t0) * 1000)
        results["inplace_applied"].append((poll_until("general:border_size", border2) - t0) * 1000)
        ok2 = json.loads(ipc("-j/getoption general:border_size")).get("int") == border2
        bad += (not ok) + (not ok2)

        print("iter %2d  eval %5.1f/%5.1f ms (spawn/ipc)  rename+reload %6.1f ms  "
              "inplace %6.1f ms  verify %5.1f/%5.1f  applied=%s/%s"
              % (i, results["eval_spawn"][-1], results["eval_ipc"][-1], results["rename"][-1],
                 results["inplace"][-1], results["verify_spawn"][-1], results["verify_ipc"][-1],
                 ok, ok2), flush=True)

    print("\nwrong value after apply: %d / %d" % (bad, iterations * 2))
    for k in results:
        v = results[k]
        print("%-8s n=%d  min %6.1f  median %6.1f  p90 %6.1f  max %6.1f  (ms)"
              % (k, len(v), min(v), statistics.median(v),
                 sorted(v)[int(len(v) * 0.9) - 1], max(v)))
    errs = hyprctl("-j", "configerrors")
    print("\nconfigerrors:", errs[:200])
    json.dump(results, open(os.path.join(HERE, "latency.json"), "w"), indent=1)


if __name__ == "__main__":
    run(int(sys.argv[1]) if len(sys.argv) > 1 else 10)
