-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Animation curves, then the animations that name them.
-- Edits here are read back into the app, not overwritten.

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.2 })

hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "easeOutQuint" })
hl.animation({ leaf = "border", enabled = false })
