-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Autostart. Top-level commands re-run on every config reload.
-- Edits here are read back into the app, not overwritten.

hl.exec_cmd("pkill -x hyprpaper")
-- Once, when Hyprland starts.
hl.on("hyprland.start", function()
  hl.exec_cmd("waybar")
  hl.exec_cmd("swaync")
  hl.dispatch(hl.dsp.exec_raw("[workspace 2 silent] kitty"))
end)
-- When Hyprland shuts down.
hl.on("hyprland.shutdown", function()
  hl.exec_cmd("hyprctl-save-state")
end)
