-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Keybinds. Order is meaning: duplicates are legal and fire in file order.
-- Edits here are read back into the app, not overwritten.

hl.bind("SUPER + Q", hl.dsp.exec_cmd("a"))
-- disabled: hl.bind("SUPER + notakey", hl.dsp.exec_cmd("kitty"), { repeating = true, description = "open a terminal" })
