-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Keybinds. Order is meaning: duplicates are legal and fire in file order.
-- Edits here are read back into the app, not overwritten.

hl.bind("SUPER + Q", hl.dsp.exec_cmd("b"))
-- disabled: hl.bind("SUPER + W", hl.dsp.exec_cmd("w"))
hl.bind("SUPER + Q", hl.dsp.exec_cmd("a"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("e"))

hl.define_submap("resize", function()
  hl.bind("right", hl.dsp.exec_cmd("grow"))
  hl.bind("left", hl.dsp.exec_cmd("shrink"))
end)
