-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Keybinds. Order is meaning: duplicates are legal and fire in file order.
-- Edits here are read back into the app, not overwritten.

hl.bind("SUPER + R", hl.dsp.submap("resize"))

hl.define_submap("resize", "landing", function()
  hl.bind("right", hl.dsp.exec_cmd("grow"))
  -- disabled: hl.bind("right", hl.dsp.exec_cmd("grow-more"))
end)

hl.define_submap("landing", function()
  hl.bind("SUPER + escape", hl.dsp.exec_cmd("leave"), { submap_universal = true })
end)

hl.define_submap("empty", function()
end)
