-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Per-device input settings. These win over the matching Input options.
-- Edits here are read back into the app, not overwritten.

hl.device({ name = "epic-mouse-v1", natural_scroll = true, sensitivity = -0.5 })
hl.device({ name = "at-translated-set-2-keyboard", kb_layout = "us,de", repeat_rate = 50 })
hl.device({ name = "my-tablet", output = "DP-1", region_position = { 10, 20 } })
