-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Section: general

hl.config({
  general = {
    gaps_in = { top = 4, right = 8, bottom = 4, left = 8 },
    gaps_out = { top = 12, right = 12, bottom = 12, left = 12 },
    col = {
      inactive_border = { colors = { "rgba(444444ff)" }, angle = 0 },
      active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)", "rgba(22ddaa80)" }, angle = 135 },
    },
  },
})
