-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Environment variables. Removing one needs a Hyprland restart to undo.
-- Edits here are read back into the app, not overwritten.

hl.env("XCURSOR_SIZE", "24")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland", true)
