-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Touchpad and touchscreen gestures.
-- Edits here are read back into the app, not overwritten.

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 4, direction = "pinchin", action = "close", mods = "SUPER" })
hl.gesture({ fingers = 3, direction = "up", action = "special", disable_inhibit = true, scale = 1.5, workspace_name = "magic" })
