-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Monitor rules. One rule per output; "" is any other display.
-- Edits here are read back into the app, not overwritten.

hl.monitor({ output = "desc:BOE 0x0791", mode = "1920x1080@60", position = "0x0", scale = 1.5 })
hl.monitor({ output = "DP-3", mode = "2560x1440@144", position = "1280x0", scale = 1, transform = 1, vrr = 1, bitdepth = 10 })
hl.monitor({ output = "HDMI-A-1", disabled = true })
hl.monitor({ output = "", mode = "preferred", position = "auto" })
