-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Monitor rules. One rule per output; "" is any other display.
-- Edits here are read back into the app, not overwritten.

hl.monitor({ output = "desc:BOE 0x0791", mode = "1920x1080@60", position = "0x0", scale = 1.5 })
hl.monitor({ output = "DP-3", mode = "2560x1440@144", position = "1280x0", scale = 1, transform = 1, vrr = 1, bitdepth = 10 })
hl.monitor({ output = "HDMI-A-1", disabled = true })
hl.monitor({ output = "DP-2", mode = "modeline 148.5 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync", scale = 1.6, reserved = { top = 32, right = 0, bottom = 0, left = 8 }, cm = "hdredid", sdr_eotf = "gamma22force", sdrbrightness = 1.4, sdrsaturation = 0.9, supports_wide_color = 1, supports_hdr = 0, sdr_min_luminance = 0.005, sdr_max_luminance = 250, min_luminance = 0.05, max_luminance = 1000, max_avg_luminance = 400 })
hl.monitor({ output = "", mode = "preferred", position = "auto" })
