-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Section: group

hl.config({
  group = {
    groupbar = {
      font_weight_active = "bold",
      text_color = "rgba(ff8800ff)",
    },
  },
})
