-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Section: decoration

hl.config({
  decoration = {
    rounding = 10,
    active_opacity = 0.95,
    shadow = {
      offset = { 0, 2 },
    },
    screen_shader = "",
  },
})
