-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Section: general

hl.config({
  general = {
    border_size = 1,
    gaps_in = { top = 5, right = 5, bottom = 5, left = 5 },
    gaps_out = { top = 5, right = 10, bottom = 15, left = 20 },
    float_gaps = -1,
    col = {
      inactive_border = { colors = { "rgba(5959aa59)" }, angle = 0 },
      active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
    },
    layout = "dwindle",
    resize_on_border = true,
  },
})
