-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Permissions. Applied on first launch, so changes need a restart.
-- Edits here are read back into the app, not overwritten.

hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/hyprlock", type = "keyboard", mode = "deny" })
