-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Plugins, loaded in this order. A disabled one is kept as a comment.
-- Edits here are read back into the app, not overwritten.

hl.plugin.load("/home/me/plugins/Hyprspace.so")
-- disabled: hl.plugin.load("/usr/lib/hyprland-plugins/libhyprexpo.so")
