-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Plugins, loaded in this order. A disabled one is kept as a comment.
-- Edits here are read back into the app, not overwritten.

hl.plugin.load("/usr/lib/hyprland-plugins/libhyprbars.so")
-- disabled: hl.plugin.load("/home/me/.local/share/hyprpm/hyprexpo.so")
hl.plugin.load("/opt/odd \"quoted\" & spaced/libborders-plus-plus.so")
