-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Monitor rules. One rule per output; "" is any other display.
-- Edits here are read back into the app, not overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@60", position = "0x0" })
hl.monitor({ output = "desc:Dell U2720Q", mode = "2560x1440@60", position = "1920x0" })
hl.monitor({ output = "", mode = "preferred" })

-- Generated by hyprtweaker 0.0.0-test. Do not edit: this file is rewritten.
-- Workspace rules. One rule per selector; Hyprland merges duplicates.
-- Edits here are read back into the app, not overwritten.

hl.workspace_rule({ workspace = "1", default = true, monitor = "desc:Dell U2720Q" })
hl.workspace_rule({ workspace = "2", persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "eDP-1" })
