-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Layer rules. Order is meaning: later rules win per effect.
-- Edits here are read back into the app, not overwritten.

hl.layer_rule({ match = { namespace = "^(rofi)$" }, blur = true })
hl.layer_rule({ name = "bar", enabled = false, match = { namespace = "waybar" }, ignore_alpha = 0.2, order = 1 })
