-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Window rules. Order is meaning: later rules win per effect.
-- Edits here are read back into the app, not overwritten.

hl.window_rule({ match = { class = "^(kitty)$" }, float = true, center = true })
hl.window_rule({ name = "pip", match = { title = "^(Picture-in-Picture)$", float = true }, pin = true, opacity = "0.9 override" })
hl.window_rule({ enabled = false, match = { class = "negative:^(firefox)$" }, no_blur = true })
hl.window_rule({ match = { workspace = "special:scratch" }, ["plugin:hy3:tab"] = "on", size = { "50%", "50%" } })
