-- Generated by hyprtweaker 0.1.0. Do not edit: this file is rewritten.
-- Workspace rules. One rule per selector; Hyprland merges duplicates.
-- Edits here are read back into the app, not overwritten.

hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "special:scratch", gapsout = 40 })
