"""The Bridge: external theming tools emitting Lua the Entrypoint requires (ADR-0006).

`registry` is what the app knows about each v1 tool -- its module, the line that loads it,
the Options it sets, how to detect it, its Template pack. `entries` is what the Manifest
records per wired module, the state that decides its Entrypoint line, and the Color source
derived from those lines (ADR-0014).

The app never writes a Bridge module and never runs a tool from here: wiring a tool's own
config is #166, behind consent.
"""

from __future__ import annotations

from .entries import (
    ACTIVE,
    WAITING,
    Active,
    BridgeEntry,
    BridgeState,
    ChosenSource,
    ColorSource,
    ManualColors,
    Off,
    PresetColors,
    Several,
    Waiting,
    Wallpaper,
    bridge_states_for,
    bridges_from_entrypoint,
    color_source_of,
    entries_for,
    files_present,
    has_run,
    in_require_order,
    owners,
    render_line,
    source_name,
    with_presence,
)
from .registry import (
    DMS,
    MATUGEN,
    NOCTALIA,
    REGISTRY,
    SHELL_SWITCH,
    WALLUST,
    BridgeModule,
    Choice,
    Detection,
    Mechanism,
    Number,
    Parameter,
    TemplateFile,
    TemplatePack,
    ToolSpec,
    VersionState,
    is_color_key,
    same_module,
    spec_for_module,
    version_state,
)

__all__ = [
    "ACTIVE",
    "DMS",
    "MATUGEN",
    "NOCTALIA",
    "REGISTRY",
    "SHELL_SWITCH",
    "WAITING",
    "WALLUST",
    "Active",
    "BridgeEntry",
    "BridgeModule",
    "BridgeState",
    "Choice",
    "ChosenSource",
    "ColorSource",
    "Detection",
    "ManualColors",
    "Mechanism",
    "Number",
    "Off",
    "Parameter",
    "PresetColors",
    "Several",
    "TemplateFile",
    "TemplatePack",
    "ToolSpec",
    "VersionState",
    "Waiting",
    "Wallpaper",
    "bridge_states_for",
    "bridges_from_entrypoint",
    "color_source_of",
    "entries_for",
    "files_present",
    "has_run",
    "in_require_order",
    "is_color_key",
    "owners",
    "render_line",
    "same_module",
    "source_name",
    "spec_for_module",
    "version_state",
    "with_presence",
]
