"""Rendering a nested Lua table, deterministically.

The writer's whole output is one shape -- `hl.config({ ... })` around a tree of tables --
so this module is small on purpose: build a tree whose leaves are *already* Lua source
(the value types render their own literals, `model/values.py`), then print it.

Determinism is the requirement that shapes everything here. The Manifest stores a content
hash per Module and the Apply transaction skips a write whose bytes did not change, so a
renderer that reordered keys or spelled a number two ways would produce phantom writes,
phantom reloads and phantom hand-edit warnings.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import Any, TypeAlias

from ..model.values import lua_string

INDENT = "  "

GENERATED_BANNER = "-- Generated by hyprtweaker {version}. Do not edit: this file is rewritten."
"""The first line of every file the app generates.

Here rather than in `modules.py` because both renderers need it -- Option Modules and the
`binds.lua` Entity Module -- and two copies of the sentence that tells a user their edits
will be lost is one copy too many.
"""


def render_entity_module(calls: list[str], *, comment: str, app_version: str) -> str | None:
    """The shared Entity Module shell: banner, one comment line, one call per line.

    `None` for an empty list so the writer prunes the Module -- absence is how this
    config model spells "no rules", the same as for binds. Shared by the rule and
    monitor renderers, so the three sentences a user reads at the top of every Entity
    Module exist exactly once.
    """
    if not calls:
        return None
    header = (
        f"{GENERATED_BANNER.format(version=app_version)}\n"
        f"-- {comment}\n"
        f"-- Edits here are read back into the app, not overwritten.\n"
    )
    return header + "\n" + "\n".join(calls) + "\n"


def ordered_fields(
    fields: Mapping[str, Any], *, first: Sequence[str] = ()
) -> list[tuple[str, Any]]:
    """An Entity's field table in a canonical order: `first` as listed, then alphabetical.

    Determinism again (see the module docstring), but for a reason the Option renderer does
    not have. An Entity's fields make a *round trip*: the app writes them, and reads its own
    Module back through the Lua recorder to adopt hand edits. The recorder hands back a Lua
    table, whose key order is not the file's -- so "emit the fields as held" spells one
    entity two ways depending on whether the model was last filled by an editor or by a
    read. That is a changed content hash with no changed meaning: a phantom write, a
    phantom reload, and a hand-edit warning about an edit nobody made.

    `first` carries the keys whose position is meaning rather than convention -- the ones a
    reader looks for to tell what an entity *is*, like a curve's `type` -- so the rest can
    be sorted without making the file harder to read than the one a human would have
    written.
    """
    remaining = {key: value for key, value in fields.items() if key not in first}
    leading = [(key, fields[key]) for key in first if key in fields]
    return [
        (key, canonical_number(value)) for key, value in leading + sorted(remaining.items())
    ]


def canonical_number(value: Any) -> Any:
    """`1.0` as `1`, recursively -- the other half of the round-trip determinism above.

    The hyprlang Importer parses every bezier coordinate and every speed as a Python
    `float`, so it produces `1.0` where a user wrote `1`. Lua has no such distinction to
    preserve: the recorder hands `1.0` back as an integer, so the second render of an
    entity the first render wrote would spell the same number differently -- one phantom
    write per Module on the first startup after an import. Canonicalising here means the
    file says what the user typed, and says it the same way every time.

    Safe in the direction it goes: every field that takes a float takes an integer too,
    while several that want an integer (`repeat_rate`, `fingers`) would be handed a `.0`
    they have no parser for.
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, Mapping):
        return {key: canonical_number(item) for key, item in value.items()}
    if isinstance(value, Sequence) and not isinstance(value, str | bytes):
        return [canonical_number(item) for item in value]
    return value


LUA_KEYWORDS = frozenset(
    {
        "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
        "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return",
        "then", "true", "until", "while",
    }
)  # fmt: skip

_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

LuaTree: TypeAlias = dict[str, "str | LuaTree"]
"""A table: keys to either a rendered Lua literal or a nested table.

Leaves are *already* Lua source. Keeping the tree that way means this module never has to
know what a gradient is -- the value types render themselves (`model/values.py`), and the
one place that could get a literal wrong stays one place.
"""


def table_key(key: str, *, spaced: bool = True) -> str:
    """`foo = ` for a plain identifier, `["foo"] = ` for anything else.

    Hyprland's key vocabulary happens to be all identifiers today, but `end` and `repeat`
    are exactly the kind of name a future section could take, and a bare `end = 1` is a
    syntax error rather than a wrong value -- it would take the entire Module down.

    `spaced=False` drops the padding for the one-line Eval preview form. The choice of
    *bracketing* is the part that matters and it is made once either way, so a preview and
    the Module written after it can never disagree about which keys need quoting.
    """
    assignment = " = " if spaced else "="
    if _IDENTIFIER.match(key) and key not in LUA_KEYWORDS:
        return f"{key}{assignment}"
    return f"[{lua_string(key)}]{assignment}"


def render_table(tree: LuaTree, depth: int = 0) -> str:
    """A nested Lua table literal, one entry per line, insertion order preserved.

    Insertion order is the caller's promise: the model hands over Options in Hyprland's own
    declaration order, so the generated file reads in the same order as the wiki and as
    `hyprctl descriptions`.
    """
    if not tree:
        return "{}"

    pad = INDENT * (depth + 1)
    lines = ["{"]
    for key, value in tree.items():
        rendered = render_table(value, depth + 1) if isinstance(value, dict) else value
        lines.append(f"{pad}{table_key(key)}{rendered},")
    lines.append(f"{INDENT * depth}}}")
    return "\n".join(lines)


def render_table_inline(tree: LuaTree) -> str:
    """The same table on one line -- what the Eval preview puts on the socket (ADR-0010).

    A preview is one request per drag tick and the request *is* the code, so the newlines
    and the indentation that make a Module readable are bytes on the wire nobody reads.
    Same keys, same order, same already-rendered leaves as `render_table`: the preview and
    the Apply transaction that makes it durable render one value exactly one way.
    """
    if not tree:
        return "{}"

    parts = []
    for key, value in tree.items():
        rendered = render_table_inline(value) if isinstance(value, dict) else value
        parts.append(f"{table_key(key, spaced=False)}{rendered}")
    return "{" + ",".join(parts) + "}"


def insert(tree: LuaTree, path: tuple[str, ...], literal: str) -> None:
    """Place a rendered literal at a dotted path, creating the intermediate tables.

    Raises rather than overwriting when a path would have to pass *through* a leaf: that
    means the Schema declared both `a.b` and `a.b.c` as values, which no `hl.config` table
    can express and which the generator should never produce.
    """
    node = tree
    for step in path[:-1]:
        branch = node.setdefault(step, {})
        if not isinstance(branch, dict):
            raise ValueError(f"{'.'.join(path)} passes through the leaf {step!r}")
        node = branch

    if isinstance(node.get(path[-1]), dict):
        raise ValueError(f"{'.'.join(path)} is already a table")
    node[path[-1]] = literal
