"""Rendering one Module per Section, and the Entrypoint that requires them.

Two renderers, both pure: model in, Lua text out. Nothing here touches the filesystem --
that is `writer.Writer`, which needs these to be pure so it can render, syntax-gate, and
only then decide whether the bytes are worth writing at all.

**One Module per Section.** `hl.config` merges per leaf, so a config split across 21 files
that each set disjoint keys means the same thing as one file that sets all of them
(research `lua-api-surface.md` §1). Splitting buys per-file blast radius: each `require`d
module runs in its own pcall scope, so a broken Module loses its own values and nothing
else -- and rollback is restoring one file's previous bytes.

**Absence is the default.** Unset Options are simply not in the tree. Nothing is emitted to
say "leave this alone", because a reload resets every value first.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from ..model.values import lua_literal_for
from ..paths import OPTIONS_DIR
from ..schema import ResolvedOption
from .lua import LuaTree, insert, render_table

GENERATED_BANNER = "-- Generated by hyprtweaker {version}. Do not edit: this file is rewritten."


def module_stem(option: ResolvedOption) -> str:
    """The Module filename stem for an Option's Section.

    The Lua spelling of the Section (`input_capture`), not the hyprctl spelling
    (`input-capture`): it is the same token that opens the table inside the file, and it is
    guaranteed to be a plain identifier, so no Section can ever need a quoted require path.
    """
    return option.path[0]


def module_relpath(option: ResolvedOption) -> str:
    """Where a Section's Module lives inside the App dir.

    `options/` is a subdirectory rather than a flat `<section>.lua` because `binds` is both
    a Section and an Entity kind, and the two Modules would collide (ADR-0005).
    """
    return f"{OPTIONS_DIR}/{module_stem(option)}.lua"


def is_option_module(relpath: str) -> bool:
    """Whether an App-dir-relative path is one of the Modules *this* writer owns.

    The inverse of `module_relpath`, and its neighbour so that moving `options/` is one
    edit. Entity Modules (`binds.lua`, `monitors.lua`, ... -- #64 and later) live beside
    them and are emphatically not this writer's to prune.
    """
    return relpath.startswith(f"{OPTIONS_DIR}/") and relpath.endswith(".lua")


def render_module(
    items: Sequence[tuple[ResolvedOption, Any]],
    *,
    app_version: str,
) -> str:
    """One Section's `hl.config` Module.

    `items` are `(option, value)` pairs from `ConfigModel`, already in Hyprland's
    declaration order and already all from the same Section.
    """
    if not items:
        raise ValueError("a Module needs at least one set Option")

    sections = {option.section for option, _ in items}
    if len(sections) != 1:
        raise ValueError(f"a Module holds exactly one Section, got {sorted(sections)}")

    tree: LuaTree = {}
    for option, value in items:
        insert(tree, option.path, lua_literal_for(option, value))

    body = render_table(tree)
    return (
        f"{GENERATED_BANNER.format(version=app_version)}\n"
        f"-- Section: {items[0][0].section}\n"
        f"\n"
        f"hl.config({body})\n"
    )


def render_entrypoint(
    *,
    modules: Sequence[str],
    legacy: str | None,
    bridges: Sequence[str],
    user: str | None,
    app_version: str,
) -> str:
    """The generated `hyprland.lua`: a header and a require list, in the one right order.

    The order is the app's whole override story (ADR-0005, ADR-0006):

    1. **generated Modules** -- what the GUI owns;
    2. **`legacy`** -- imported constructs the GUI cannot represent, so they sit above the
       generated values they may need to correct;
    3. **`bridge/*`** -- external tools (matugen, wallust, ...), which must beat the GUI or
       live theming silently stops working;
    4. **`user`** -- last, so the escape hatch actually escapes. The app never fights it; it
       badges Options `user.lua` overrides instead.

    Only files that exist are required: Hyprland's `require` is protected, and asking for a
    `user.lua` the user never created would add an error to every reload.
    """
    lines = [
        GENERATED_BANNER.format(version=app_version),
        "-- Regenerated whenever the module set changes; directories are not watched.",
        "",
    ]

    def block(comment: str, requires: Sequence[str]) -> None:
        if not requires:
            return
        lines.append(f"-- {comment}")
        lines.extend(f'require("{path}")' for path in requires)
        lines.append("")

    block("Settings written by hyprtweaker.", modules)
    block(
        "Imported constructs the GUI cannot represent. Never rewritten.",
        [legacy] if legacy else [],
    )
    block("External tools. Owned by the tool, not by hyprtweaker.", bridges)
    block("Your own Lua. Required last, so it wins. Never rewritten.", [user] if user else [])

    return "\n".join(lines).rstrip("\n") + "\n"
