"""Golden files over the rendered Lua: model in, exact bytes out.

Golden rather than assertion-per-line because the writer's product *is* text a user reads
and a compositor parses. A change to a colour spelling or an indent is a change to their
config file, and a golden makes it a reviewable diff instead of a surprise on reload.

Regenerate deliberately, never reflexively::

    UPDATE_GOLDEN=1 pytest tests/unit/test_writer_modules.py

Read the diff first. A regenerated golden nobody read converts a failing test into a silent
change to everybody's `~/.config/hypr`.
"""

from __future__ import annotations

import os

import pytest
from _support import GOLDEN_DIR, SAMPLE_APP_VERSION, SAMPLE_VERSION, SCHEMA_DIR, sample_model

from hyprtweaker.engine.model import (
    Color,
    ConfigModel,
    CssGaps,
    Gradient,
    Vec2,
    display_text,
    parse_value,
)
from hyprtweaker.engine.schema import OptionType, load_schema
from hyprtweaker.engine.writer import module_relpath, render_module, syntax

WRITER_GOLDEN_DIR = GOLDEN_DIR / "writer"


@pytest.fixture(scope="module")
def model() -> ConfigModel:
    return sample_model()


@pytest.fixture(scope="module")
def modules(model: ConfigModel) -> dict[str, str]:
    return {
        module_relpath(model.section(section)[0][0]): render_module(
            model.section(section), app_version=SAMPLE_APP_VERSION
        )
        for section in model.sections()
    }


def _golden(relpath: str, actual: str) -> None:
    golden = WRITER_GOLDEN_DIR / relpath.replace("/", "-")

    if os.environ.get("UPDATE_GOLDEN"):
        golden.parent.mkdir(parents=True, exist_ok=True)
        golden.write_text(actual, encoding="utf-8")
        pytest.skip(f"regenerated {golden.name}")

    assert golden.is_file(), (
        f"missing golden file {golden}; create it with UPDATE_GOLDEN=1 and read the diff"
    )
    assert actual == golden.read_text(encoding="utf-8"), (
        f"{relpath} no longer renders as {golden.name}. If the change is intended, "
        "regenerate with UPDATE_GOLDEN=1 and review the diff in the PR."
    )


class TestGoldens:
    @pytest.mark.parametrize(
        "relpath",
        [
            "options/general.lua",
            "options/decoration.lua",
            "options/group.lua",
            "options/misc.lua",
            "options/input_capture.lua",
        ],
    )
    def test_module_matches_golden(self, modules: dict[str, str], relpath: str) -> None:
        assert relpath in modules, f"the sample model no longer produces {relpath}"
        _golden(relpath, modules[relpath])

    def test_the_golden_set_is_the_whole_module_set(self, modules: dict[str, str]) -> None:
        """Guards the goldens themselves: a Module nobody golden-checked is unchecked."""
        checked = {path.name for path in WRITER_GOLDEN_DIR.glob("options-*.lua")}
        assert {relpath.replace("/", "-") for relpath in modules} == checked


class TestModuleShape:
    def test_one_module_per_section(self, modules: dict[str, str]) -> None:
        assert set(modules) == {
            "options/general.lua",
            "options/decoration.lua",
            "options/group.lua",
            "options/misc.lua",
            "options/input_capture.lua",
        }

    def test_a_dashed_section_gets_its_lua_spelling(self, modules: dict[str, str]) -> None:
        """`input-capture` is not a Lua identifier; `input_capture` is, in file and table."""
        assert "input_capture = {" in modules["options/input_capture.lua"]

    def test_unset_options_are_absent(self, modules: dict[str, str]) -> None:
        """Omission *is* "Hyprland's default" -- a reload resets every value first."""
        general = modules["options/general.lua"]
        assert "gaps_workspaces" not in general
        assert "no_focus_fallback" not in general

    def test_an_option_set_to_its_own_default_is_still_emitted(
        self, model: ConfigModel, modules: dict[str, str]
    ) -> None:
        assert model.schema["general:border_size"].default == 1
        assert "border_size = 1," in modules["options/general.lua"]

    def test_every_module_is_a_single_hl_config_call(self, modules: dict[str, str]) -> None:
        for relpath, text in modules.items():
            assert text.count("hl.config(") == 1, relpath
            assert text.endswith("})\n"), relpath

    def test_every_module_says_it_is_generated(self, modules: dict[str, str]) -> None:
        for relpath, text in modules.items():
            assert text.startswith("-- Generated by hyprtweaker"), relpath


class TestComplexValues:
    def test_gradients_emit_as_tables(self, modules: dict[str, str]) -> None:
        """ADR-0005: Lua refuses `descriptions`' gradient text; tables are mandatory."""
        general = modules["options/general.lua"]
        assert (
            'active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },'
            in general
        )
        assert "45deg" not in general

    def test_a_single_stop_gradient_is_still_a_table(self, modules: dict[str, str]) -> None:
        """No degradation to a bare string: one shape reads better in a diff."""
        assert (
            'inactive_border = { colors = { "rgba(5959aa59)" }, angle = 0 },'
            in modules["options/general.lua"]
        )

    def test_css_gaps_emit_as_tables(self, modules: dict[str, str]) -> None:
        general = modules["options/general.lua"]
        assert "gaps_in = { top = 5, right = 5, bottom = 5, left = 5 }," in general
        assert "gaps_out = { top = 5, right = 10, bottom = 15, left = 20 }," in general

    def test_vec2_emits_as_an_array(self, modules: dict[str, str]) -> None:
        assert "offset = { 0, 2 }," in modules["options/decoration.lua"]

    def test_an_explicit_null_emits_its_curated_value(self, modules: dict[str, str]) -> None:
        assert "float_gaps = -1," in modules["options/general.lua"]
        assert 'screen_shader = "",' in modules["options/decoration.lua"]

    def test_a_font_weight_name_stays_a_string(self, modules: dict[str, str]) -> None:
        assert 'font_weight_active = "bold",' in modules["options/group.lua"]


class TestDeterminism:
    def test_rendering_twice_gives_identical_bytes(self, model: ConfigModel) -> None:
        """The Manifest hashes these bytes; a wobbling renderer means phantom reloads."""
        first = render_module(model.section("general"), app_version=SAMPLE_APP_VERSION)
        second = render_module(model.section("general"), app_version=SAMPLE_APP_VERSION)
        assert first == second

    def test_insertion_order_does_not_change_the_output(self, model: ConfigModel) -> None:
        reversed_model = ConfigModel(model.schema)
        for option, value in reversed(model.set_options()):
            if value is None:
                reversed_model.set_null(option.name)
            else:
                reversed_model.set(option.name, value)

        assert render_module(
            reversed_model.section("general"), app_version=SAMPLE_APP_VERSION
        ) == render_module(model.section("general"), app_version=SAMPLE_APP_VERSION)


class TestSyntaxGate:
    """AC: every written output passes `luac -p` (ADR-0010, step 3)."""

    @pytest.fixture(autouse=True)
    def _require_luac(self) -> None:
        """Skip these without `luac`, unless the machine promised to have one.

        `luac` is a dev tool, not a runtime dependency, so a contributor without it still
        gets a green suite. CI installs it on purpose and sets `HYPRTWEAKER_REQUIRE_LUAC=1`,
        where a skip would mean the install regressed -- and a silently skipped gate is
        exactly the "no tests ran, therefore pass" failure this repo refuses elsewhere.
        """
        if syntax.gate_available():
            return
        if os.environ.get("HYPRTWEAKER_REQUIRE_LUAC"):
            pytest.fail("HYPRTWEAKER_REQUIRE_LUAC is set but no luac was found")
        pytest.skip("no luac on this machine; the syntax gate degrades to a no-op")

    def test_every_module_parses(self, modules: dict[str, str]) -> None:
        for relpath, text in modules.items():
            syntax.gate(text, relpath)

    def test_the_gate_actually_rejects_broken_lua(self) -> None:
        """Guards the gate itself: a check that passes everything is not a check."""
        with pytest.raises(syntax.LuaSyntaxError):
            syntax.gate("hl.config({ = 1 })", "broken.lua")

    def test_the_failure_names_the_module_not_a_temp_path(self) -> None:
        """The message reaches a bug report; `/tmp/xyz/module.lua` tells nobody anything."""
        result = syntax.check("hl.config({ = 1 })", "options/general.lua")

        assert not result.ok
        assert "options/general.lua" in result.detail


@pytest.fixture(scope="module")
def edited() -> str:
    """One Section rendered from values built the way the complex editors build them."""
    model = ConfigModel(load_schema(SAMPLE_VERSION, SCHEMA_DIR))
    model.set(
        "general:col.active_border",
        Gradient(
            (Color(0xEE33CCFF), Color(0xEE00FF99), Color(0x8022DDAA)),
            # A `GtkScale` reads a float; `descriptions` prints a whole float without its
            # `.0`, and so must the writer, or the content hash moves for nothing.
            135.0,
        ),
    )
    model.set("general:col.inactive_border", Gradient((Color(0xFF444444),)))
    model.set("general:gaps_in", CssGaps(4, 8, 4, 8))
    model.set("general:gaps_out", CssGaps.uniform(12))
    return render_module(model.section("general"), app_version=SAMPLE_APP_VERSION)


class TestEditedValues:
    """The values the complex editors build, rendered (#58).

    Everything above starts from display text -- a schema default, an imported `.conf` line.
    The editors do not: a colour button hands the model a `Color`, a gradient's stop row a
    `Gradient` of them, four spin buttons a `CssGaps`. Same classes, reached a different way,
    and the way that matters most because a gradient reaching `hl.config` as a string is a
    config error rather than a wrong colour (ADR-0005).

    So this is a golden over exactly the shapes an editor can produce: a gradient the user
    added a third stop to and dragged to 135°, gaps typed side by side, gaps flattened back
    to uniform.
    """

    def test_the_edited_module_matches_its_golden(self, edited: str) -> None:
        _golden("edits/general.lua", edited)

    def test_an_edited_gradient_still_reaches_lua_as_a_table(self, edited: str) -> None:
        assert "135deg" not in edited
        assert "angle = 135 }" in edited

    def test_edited_values_survive_the_trip_through_display_text(self) -> None:
        """The third representation, and the one the compositor answers Read-back in.

        An editor's value has to mean the same thing after a `descriptions`-spelling round
        trip, or the Apply transaction that wrote it would report its own write as a
        mismatch and ADR-0016 would badge the Row "didn't apply".
        """
        values = (
            Gradient((Color(0xEE33CCFF), Color(0x8022DDAA)), 135.0),
            CssGaps(4, 8, 4, 8),
            CssGaps.uniform(12),
            Vec2(0.0, 2.0),
            Color(0xFF8800FF),
        )
        for value in values:
            assert parse_value(_TYPE_OF[type(value)], display_text(value)) == value


_TYPE_OF = {
    Gradient: OptionType.GRADIENT,
    CssGaps: OptionType.CSS_GAPS,
    Vec2: OptionType.VEC2,
    Color: OptionType.COLOR,
}
