"""First-run detection: which of ADR-0009's four cases a config dir is in.

The routing decision is the one the whole first-run experience hangs off, and getting it
wrong in one particular direction -- calling a hand-written `hyprland.lua` "ours" -- is the
outcome ADR-0009 forbids outright, because the Writer would then regenerate over it. That
asymmetry is what the uncertain-case tests below are pinning down.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from _support import SAMPLE_APP_VERSION, SAMPLE_VERSION

from hyprtweaker.engine.migration.detect import (
    ConfigKind,
    detect,
    has_autogenerated_marker,
)
from hyprtweaker.engine.paths import ConfigPaths
from hyprtweaker.engine.state import Manifest
from hyprtweaker.engine.state.manifest import ModuleRecord


@pytest.fixture
def paths(tmp_path: Path) -> ConfigPaths:
    config = ConfigPaths.rooted_at(tmp_path)
    config.hypr_dir.mkdir(parents=True)
    return config


def run(paths: ConfigPaths) -> object:
    return detect(paths, app_version=SAMPLE_APP_VERSION, schema_version=SAMPLE_VERSION)


def write_manifest_claiming(paths: ConfigPaths, entrypoint_text: str) -> None:
    """A Manifest that vouches for an Entrypoint with these exact bytes."""
    paths.app_dir.mkdir(parents=True, exist_ok=True)
    manifest = Manifest(
        app_version=SAMPLE_APP_VERSION,
        schema_version=SAMPLE_VERSION,
        entrypoint=ModuleRecord.of(entrypoint_text, ()),
        modules={},
    )
    paths.manifest.write_text(manifest.render(), encoding="utf-8")


class TestFourCases:
    def test_nothing_at_all_is_a_fresh_start(self, paths: ConfigPaths) -> None:
        found = run(paths)

        assert found.kind is ConfigKind.FRESH
        assert found.source is None
        assert not found.offers_import

    def test_only_a_conf_routes_to_the_hyprlang_wizard(self, paths: ConfigPaths) -> None:
        paths.hyprland_conf.write_text("general {\n  gaps_in = 5\n}\n", encoding="utf-8")

        found = run(paths)

        assert found.kind is ConfigKind.LEGACY_CONF
        assert found.source == paths.hyprland_conf
        assert found.offers_import

    def test_an_entrypoint_the_manifest_vouches_for_is_a_normal_run(
        self, paths: ConfigPaths
    ) -> None:
        text = 'require("hyprtweaker/options/general")\n'
        paths.entrypoint.write_text(text, encoding="utf-8")
        write_manifest_claiming(paths, text)

        found = run(paths)

        assert found.kind is ConfigKind.APP_GENERATED
        assert not found.hand_edited
        assert not found.offers_import

    def test_a_lua_file_no_manifest_claims_is_foreign(self, paths: ConfigPaths) -> None:
        paths.entrypoint.write_text(
            "hl.config({ general = { gaps_in = 5 } })\n", encoding="utf-8"
        )

        found = run(paths)

        assert found.kind is ConfigKind.FOREIGN_LUA
        assert found.source == paths.entrypoint
        assert found.offers_import


class TestTheUncertainCase:
    """A `hyprland.lua` with no claim on it must never be treated as the app's own.

    Being wrong the safe way re-imports a file the app generated: untidy, and the original
    is kept either way. Being wrong the other way lets the Writer regenerate over a config
    the user hand-wrote, which is unrecoverable.
    """

    def test_a_missing_manifest_reads_as_foreign(self, paths: ConfigPaths) -> None:
        paths.entrypoint.write_text("hl.config({})\n", encoding="utf-8")

        assert run(paths).kind is ConfigKind.FOREIGN_LUA

    def test_a_damaged_manifest_reads_as_foreign(self, paths: ConfigPaths) -> None:
        paths.entrypoint.write_text("hl.config({})\n", encoding="utf-8")
        paths.app_dir.mkdir(parents=True, exist_ok=True)
        paths.manifest.write_text("{not json", encoding="utf-8")

        assert run(paths).kind is ConfigKind.FOREIGN_LUA

    def test_a_manifest_that_claims_the_file_but_disagrees_is_a_hand_edit(
        self, paths: ConfigPaths
    ) -> None:
        """Not foreign: the app knows it wrote this one, so the answer is the consent gate.

        Offering to "import" here would mean offering the user their own generated config
        back over itself.
        """
        write_manifest_claiming(paths, "-- what we wrote\n")
        paths.entrypoint.write_text("-- what they edited it into\n", encoding="utf-8")

        found = run(paths)

        assert found.kind is ConfigKind.APP_GENERATED
        assert found.hand_edited
        assert not found.offers_import


class TestAutogeneratedMarker:
    """Hyprland's own example config skips the loss report -- it is not the user's work."""

    def test_the_stock_example_config_is_recognised(self, paths: ConfigPaths) -> None:
        paths.hyprland_conf.write_text(
            "# This is an example Hyprland config file.\nautogenerated = 1 # remove this\n",
            encoding="utf-8",
        )

        found = run(paths)

        assert found.autogenerated
        assert found.streamlined

    def test_a_real_config_is_not(self, paths: ConfigPaths) -> None:
        paths.hyprland_conf.write_text("general {\n  gaps_in = 5\n}\n", encoding="utf-8")

        found = run(paths)

        assert not found.autogenerated
        assert not found.streamlined

    def test_a_comment_mentioning_the_marker_is_not_the_marker(self, tmp_path: Path) -> None:
        """Matched on the assignment, not the word.

        A user who deleted the marker and left the comment explaining it must keep their
        loss report -- skipping it treats their work as Hyprland's boilerplate.
        """
        conf = tmp_path / "hyprland.conf"
        conf.write_text("# I removed autogenerated = 1 from this file\n", encoding="utf-8")

        assert not has_autogenerated_marker(conf)

    def test_a_marker_turned_off_is_not_a_marker(self, tmp_path: Path) -> None:
        conf = tmp_path / "hyprland.conf"
        conf.write_text("autogenerated = 0\n", encoding="utf-8")

        assert not has_autogenerated_marker(conf)


def test_settings_are_read_only_exactly_while_an_import_is_on_offer(
    paths: ConfigPaths,
) -> None:
    """ADR-0009: pages show but refuse to save until the offered import is accepted.

    There is nowhere honest to write while the live session is reading a file this app
    does not own.
    """
    paths.hyprland_conf.write_text("general {\n  gaps_in = 5\n}\n", encoding="utf-8")
    assert run(paths).read_only

    paths.hyprland_conf.unlink()
    assert not run(paths).read_only
