"""The canonical `binds.lua` Module: rendering, and reading it back (ADR-0007, #64)."""

from __future__ import annotations

import pytest

from hyprtweaker.engine.model import ConfigModel
from hyprtweaker.engine.model.entities import (
    Bind,
    BindDevice,
    BindOptions,
    DispatcherCall,
    EntitySet,
    Submap,
    Unbind,
)
from hyprtweaker.engine.paths import BINDS_MODULE
from hyprtweaker.engine.writer.binds import parse_binds_module, render_binds_module

VERSION = "0.1.0"


def _schema():  # type: ignore[no-untyped-def]
    from hyprtweaker.engine.schema import load_schema

    return load_schema("0.56.2")


def render(entities: EntitySet) -> str:
    text = render_binds_module(entities, app_version=VERSION)
    assert text is not None
    return text


def exec_bind(keys: str, command: str, **kwargs: object) -> Bind:
    return Bind(
        keys=keys,
        dispatcher=DispatcherCall(path="exec_cmd", positional=(command,)),
        **kwargs,  # type: ignore[arg-type]
    )


class TestRender:
    def test_no_binds_renders_no_module(self) -> None:
        assert render_binds_module(EntitySet(), app_version=VERSION) is None

    def test_simple_bind(self) -> None:
        """Exec takes a bare string: the table form is a config error in 0.56.2."""
        text = render(EntitySet(binds=[exec_bind("SUPER + Q", "kitty")]))
        assert 'hl.bind("SUPER + Q", hl.dsp.exec_cmd("kitty"))' in text

    def test_banner_warns_the_file_is_rewritten(self) -> None:
        assert "Generated by hyprtweaker" in render(EntitySet(binds=[exec_bind("A", "x")]))

    def test_positional_dispatcher_keeps_bare_arguments(self) -> None:
        bind = Bind(
            keys="SUPER + R", dispatcher=DispatcherCall(path="submap", positional=("resize",))
        )
        assert 'hl.dsp.submap("resize")' in render(EntitySet(binds=[bind]))

    def test_dispatcher_with_no_arguments(self) -> None:
        bind = Bind(keys="SUPER + M", dispatcher=DispatcherCall(path="exit"))
        assert "hl.dsp.exit()" in render(EntitySet(binds=[bind]))

    def test_nested_dispatcher_namespace(self) -> None:
        bind = Bind(keys="SUPER + C", dispatcher=DispatcherCall(path="window.close"))
        assert "hl.dsp.window.close()" in render(EntitySet(binds=[bind]))

    def test_booleans_render_as_lua_not_python(self) -> None:
        """`DispatcherCall.__str__` is a debug string using `repr`; emission must not be."""
        bind = Bind(keys="A", dispatcher=DispatcherCall(path="focus", args={"silent": True}))
        text = render(EntitySet(binds=[bind]))
        assert "silent = true" in text
        assert "True" not in text

    def test_flags_render_as_an_options_table(self) -> None:
        bind = exec_bind("SUPER + Q", "kitty", options=BindOptions(locked=True, repeating=True))
        text = render(EntitySet(binds=[bind]))
        assert "{ locked = true, repeating = true }" in text

    def test_description_renders(self) -> None:
        bind = exec_bind("SUPER + Q", "kitty", options=BindOptions(description="Open terminal"))
        assert 'description = "Open terminal"' in render(EntitySet(binds=[bind]))

    def test_device_renders_as_a_table(self) -> None:
        bind = exec_bind(
            "SUPER + Q",
            "kitty",
            options=BindOptions(device=BindDevice(inclusive=False, names=("kbd1", "kbd2"))),
        )
        text = render(EntitySet(binds=[bind]))
        assert 'device = { inclusive = false, list = { "kbd1", "kbd2" } }' in text

    def test_no_options_table_when_every_flag_is_default(self) -> None:
        text = render(EntitySet(binds=[exec_bind("SUPER + Q", "kitty")]))
        assert text.count("{") == text.count("}")
        assert ", {}" not in text

    def test_mouse_flag_is_never_emitted(self) -> None:
        """v0.56.2 never reads a `mouse` key; emitting one is a lie (ADR-0007)."""
        entities = EntitySet(
            binds=[exec_bind("SUPER + mouse:272", "kitty", options=BindOptions(drag=True))]
        )
        assert "mouse =" not in render(entities)

    def test_key_code_binds_render(self) -> None:
        """`hyprctl binds` is blind to these; the file is the only place they survive."""
        assert 'hl.bind("SUPER + code:10"' in render(
            EntitySet(binds=[exec_bind("SUPER + code:10", "x")])
        )

    def test_duplicates_and_order_are_preserved(self) -> None:
        entities = EntitySet(
            binds=[
                exec_bind("SUPER + Q", "first"),
                exec_bind("SUPER + Q", "second"),
                exec_bind("SUPER + Q", "third"),
            ]
        )
        text = render(entities)
        assert text.index("first") < text.index("second") < text.index("third")

    def test_unbind_renders(self) -> None:
        entities = EntitySet(binds=[exec_bind("A", "x")], unbinds=[Unbind(keys="SUPER + X")])
        assert 'hl.unbind("SUPER + X")' in render(entities)

    def test_submap_binds_nest_inside_define_submap(self) -> None:
        entities = EntitySet(
            submaps=[Submap(name="resize")],
            binds=[
                exec_bind("SUPER + R", "root"),
                exec_bind("right", "grow", submap="resize"),
            ],
        )
        text = render(entities)
        assert 'hl.define_submap("resize", function()' in text
        assert text.index("root") < text.index("resize")
        assert "end)" in text

    def test_submap_reset_target_renders(self) -> None:
        entities = EntitySet(
            submaps=[Submap(name="resize", reset_target="reset")],
            binds=[exec_bind("right", "grow", submap="resize")],
        )
        assert 'hl.define_submap("resize", "reset", function()' in render(entities)

    def test_deterministic(self) -> None:
        entities = EntitySet(binds=[exec_bind("SUPER + Q", "kitty")])
        assert render(entities) == render(entities)

    def test_function_valued_action_is_not_emitted(self) -> None:
        """A function action lives in user.lua; the app must not invent Lua for it."""
        entities = EntitySet(binds=[exec_bind("A", "x"), Bind(keys="B", dispatcher=None)])
        text = render(entities)
        assert 'hl.bind("B"' not in text


class TestRoundTrip:
    """Hand edits must reflect in the app, so what is written must read back (ADR-0007)."""

    def assert_round_trips(self, entities: EntitySet) -> None:
        parsed = parse_binds_module(render(entities))
        assert [(b.keys, b.submap) for b in parsed.binds] == [
            (b.keys, b.submap) for b in entities.binds if b.dispatcher is not None
        ]

    def test_simple(self) -> None:
        self.assert_round_trips(EntitySet(binds=[exec_bind("SUPER + Q", "kitty")]))

    def test_duplicates_keep_order(self) -> None:
        self.assert_round_trips(
            EntitySet(binds=[exec_bind("SUPER + Q", "a"), exec_bind("SUPER + Q", "b")])
        )

    def test_dispatcher_survives(self) -> None:
        entities = EntitySet(binds=[exec_bind("SUPER + Q", "kitty")])
        parsed = parse_binds_module(render(entities))
        assert parsed.binds[0].dispatcher is not None
        assert parsed.binds[0].dispatcher.path == "exec_cmd"
        assert parsed.binds[0].dispatcher.positional == ("kitty",)

    def test_flags_survive(self) -> None:
        entities = EntitySet(
            binds=[
                exec_bind(
                    "SUPER + Q",
                    "kitty",
                    options=BindOptions(locked=True, description="Terminal"),
                )
            ]
        )
        parsed = parse_binds_module(render(entities))
        assert parsed.binds[0].options.locked is True
        assert parsed.binds[0].options.description == "Terminal"

    def test_key_code_survives(self) -> None:
        self.assert_round_trips(EntitySet(binds=[exec_bind("SUPER + code:10", "x")]))

    def test_submap_membership_survives(self) -> None:
        self.assert_round_trips(
            EntitySet(
                submaps=[Submap(name="resize")],
                binds=[exec_bind("A", "root"), exec_bind("right", "grow", submap="resize")],
            )
        )

    def test_unrepresentable_hand_edit_is_surfaced_not_dropped(self) -> None:
        """A construct the app cannot model becomes a read-only row, never a silent loss."""
        parsed = parse_binds_module(
            'hl.bind("SUPER + Q", hl.dsp.exec_cmd{ command = "kitty" })\n'
            'hl.bind("SUPER + W", function() end)\n'
        )
        assert len(parsed.binds) == 1
        assert parsed.read_only, "the function-valued bind must be surfaced"


class TestRelpath:
    def test_binds_module_is_not_an_option_module(self) -> None:
        """`options/` is pruned against the model; an entity Module must not be caught."""
        from hyprtweaker.engine.writer.modules import is_option_module

        assert not is_option_module(BINDS_MODULE)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(pytest.main([__file__]))


class TestPruning:
    """A binds Module is only deleted on the strength of a model that actually read it."""

    def build(self, tmp_path, *, binds: bool):  # type: ignore[no-untyped-def]
        from hyprtweaker.engine.paths import BINDS_MODULE, ConfigPaths
        from hyprtweaker.engine.writer import Writer

        paths = ConfigPaths.rooted_at(tmp_path)
        paths.hypr_dir.mkdir(parents=True, exist_ok=True)
        schema = _schema()
        model = ConfigModel(schema)
        model.set("general:border_size", 2)
        if binds:
            model.entities.binds.append(exec_bind("SUPER + Q", "kitty"))
            model.mark_entities_loaded()
        return paths, model, Writer(paths, app_version=VERSION), BINDS_MODULE

    def test_a_binds_module_is_kept_when_the_model_never_read_one(self, tmp_path) -> None:  # type: ignore[no-untyped-def]
        """The regression: an unread model must not be mistaken for an emptied one.

        Session 1 writes binds.lua. Session 2 opens without reading it and the user nudges
        an unrelated Option -- and before this guard, that write deleted every bind they had.
        """
        paths, model, writer, relpath = self.build(tmp_path, binds=True)
        writer.write(model)
        assert (paths.app_dir / relpath).is_file()

        fresh = ConfigModel(model.schema)
        fresh.set("general:border_size", 4)
        assert not fresh.entities_loaded

        writer.write(fresh)

        assert (paths.app_dir / relpath).is_file(), "an unread binds.lua was pruned"

    def test_a_binds_module_is_pruned_once_the_model_has_read_it(self, tmp_path) -> None:  # type: ignore[no-untyped-def]
        """Deleting the last bind really does remove the file -- the guard is not a veto."""
        paths, model, writer, relpath = self.build(tmp_path, binds=True)
        writer.write(model)
        assert (paths.app_dir / relpath).is_file()

        model.entities.binds.clear()
        result = writer.write(model)

        assert relpath in result.removed
        assert not (paths.app_dir / relpath).is_file()
